version: "3"
services:
  server:
    container_name: movies-api
    # restart: always
    build: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    expose:
      - "3333"
    ports:
      - "3333:3333"
    environment:
      - TMDB_API_URL=https://api.themoviedb.org/3/
      - TMDB_IMAGE_STORE=https://image.tmdb.org/t/p/w200
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PORT=3333
    links:
      - redis
  client:
    container_name: client
    # restart: always
    build: ./client
    volumes:
      - ./client:/client
      - /client/node_modules
    expose:
      - "3000"
    ports:
      - "3000:3000"
    links:
      - server
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"